/glg4debug/glg4param omit_muon_processes  1.0
/glg4debug/glg4param omit_hadronic_processes  1.0

/rat/db/set DETECTOR experiment "rut"
/rat/db/set DETECTOR geo_file "rut/cylinder.geo"

/run/initialize

/PMTOpticalModel/luxlevel 0

# BEGIN EVENT LOOP

/rat/proc count
/rat/procset update 1

# Use IO.default_output_filename
/rat/proclast outroot

# END EVENT LOOP


/generator/add external external:uniform:"testIn.dat"

/run/beamOn 10
